### ISSUE TITLE
Delta Chart synchronisation 

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/identity#10]
Delta Chart enhancement #3
The delta chart should have a drill down functionality clicking on a specific bar brings up a second chart showing where the duplicates have migrated from

**Comment by Practical-DQ** [comment]
this would work bell going from the second delta chart jumping to the flow chart using the reference data as the starting node.

**Comment by danielkagemann** [comment]
so click on bar and jump to flow would be okay ?

**Comment by Practical-DQ** [comment]
jump to flow and focus set to node that user clicked on, that would be perfect

**Comment by danielkagemann** [comment]
done.
