### ISSUE TITLE
Example results tab

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/identity#11]
Separate window to visualise results
a) a random set of three results from a particular score need to shown to the user to give them a feel for the matches
b) also comparing a duplicate group from reference set to where they are now in the new result set.

**Comment by danielkagemann** [comment]
can you explain this more detailed ?

**Comment by Practical-DQ** [comment]
There should be the information from all records in the group. This contains the basics like name sweet, town, etc  and their individual scores (so at least 2 records are always shown but could be n more)
This record information in itself won't change, but the record that were interested in should be highlighted (in the same back colour blue for reference and grey for new data.) If there has been an addition then his is given a green background, if a member has fallen out then this is shown as red. We list all reduplication scores from reference and again all dediuplication scores from new data set

**Comment by danielkagemann** [comment]
so you want all groups with detailed record data to be displayed ?
would look strange for > 1000 groups

**Comment by danielkagemann** [comment]
i think it can be closed
