### ISSUE TITLE
Extra Slider for secure duplicates

### ISSUE THREAD

**Issue by Practical-DQ** [Elemetric/identity#7]
The chart needs an added slider to separate the ‘secure’ duplicates, the reaction here is different than with the bottom slider as there is no cut of point, but the measurements of groups will need to be rethought
because a duplicate group can then be either completely in the safe zone, or split across secure and the south korean demilitized zone.
its a fuckup,but well get there

**Comment by Practical-DQ** [comment]
after heavy persuasion, this should be moved to a separate sheet.
the Secure area needs to work with tiles and already existing slider Secure duplicates follow these conditions:
a) the complete group can be resolved because all members are above the threshold
b) part of the group can be resolved, because some members are above the threshhold others not (this essentially makes two separate duplicate groups where there was only one before)
c) None of the group can be resolved because all members (apasrt from header) are below the score threshold

**Comment by danielkagemann** [comment]
on which tab should we implement this ? 
dont want to make it available on every page

**Comment by Practical-DQ** [comment]
My suggestion is make a separate tab wich covers specifically secure duplicates. Set this up similar to the scores chart in the scores tab. Add check box to the other tabs, which gives the user the chance of 'berucksichtigen' of secure duplicates.

**Comment by danielkagemann** [comment]
what do you want to see on the secure duplicates tab ?
a) what kind of chart ?
b) no chart just tiles ?
c) let the user select a group like example page ?
d) something completely different
